# Generated by Django 4.0.6 on 2022-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
